### ISSUE TITLE
images and resources should not be indiscriminately cached

### ISSUE THREAD

**Issue by wenzowski** [refinery/refinerycms#1738]
Assets served from s3 look like they're being cached locally regardless of size. This is bad.

This issue presents itself when using [memcached](http://memcached.org/) via `ActiveSupport::Cache::DalliStore`, as rails tries to load multi-megabyte files into the cache.
#### Heroku Stack Trace

```
2012-06-09T01:48:41+00:00 app[web.2]: Started GET "/system/resources/BAhbBlsHOgZmSSIqMjAxMi8wNi8wOC8yMS80MS81Mi85NzMvNnRoX2dyYWRlLnBkZgY6BkVU/6th%20grade.pdf" for 69.196.135.118 at 2012-06-09 01:48:41 +0000
2012-06-09T01:48:44+00:00 app[web.2]: DalliError: Value too large, memcached can only store 1048576 bytes per key [key: 1dc59d548aefbdb08d9a4b81a86b9fd0c5109b4a, size: 5510404]
2012-06-09T01:48:44+00:00 app[web.2]: [2012-06-09 01:48:44] ERROR NoMethodError: undefined method `each' for nil:NilClass
2012-06-09T01:48:44+00:00 app[web.2]:   /app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/body_proxy.rb:26:in `method_missing'
2012-06-09T01:48:44+00:00 app[web.2]:   /app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/handler/webrick.rb:71:in `service'
2012-06-09T01:48:44+00:00 app[web.2]:   /usr/local/lib/ruby/1.9.1/webrick/httpserver.rb:111:in `service'
2012-06-09T01:48:44+00:00 app[web.2]:   /usr/local/lib/ruby/1.9.1/webrick/httpserver.rb:70:in `run'
2012-06-09T01:48:44+00:00 app[web.2]:   /usr/local/lib/ruby/1.9.1/webrick/server.rb:183:in `block in start_thread'
```
#### Gemfile

```
gem 'fog',    '~> 1.3.1'
gem 'dalli',  '~> 2.0.5'
```

**Comment by bricesanchez** [comment]
I'm facing the same problem on Refinery CMS 3.0 and Heroku.
Is your solution still ok ?
