### ISSUE TITLE
Unable to create first admin user on stable branch

### ISSUE THREAD

**Issue by andrewhavens** [refinery/refinerycms#3013]
I just installed a new Refinery app based on the stable branch as mentioned in the docs:

    rails _3.2.15_ new mywebsite.com -m http://refinerycms.com/t/2.1.0

I configured my `site_name` and `backend_route`, started the app, visited the admin, filled in my username, email, password, and upon submit saw this error:

> NoMethodError in Refinery::UsersController#create

> undefined method `name' for nil:NilClass

Here is the backtrace:

```
Started POST "/admin/users/register" for 127.0.0.1 at 2015-07-20 16:49:56 -0700
Processing by Refinery::UsersController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"j0hqgkghzKcCJh35L1SZNgKi3l3pjpoMH+vQiT7ctSg=", "user"=>{"username"=>"andrew", "email"=>"andrew@email.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "locale"=>:en}
  Refinery::Role Load (0.1ms)  SELECT "refinery_roles".* FROM "refinery_roles" WHERE "refinery_roles"."title" = 'Refinery' LIMIT 1
  Refinery::User Load (0.1ms)  SELECT "refinery_users".* FROM "refinery_users" INNER JOIN "refinery_roles_users" ON "refinery_users"."id" = "refinery_roles_users"."user_id" WHERE "refinery_roles_users"."role_id" = 1
  Refinery::User Load (0.5ms)  SELECT "refinery_users".* FROM "refinery_users" WHERE ("slug" = 'andrew' OR "slug" LIKE 'andrew--%'ESCAPE '\') ORDER BY LENGTH("slug") DESC, "slug" DESC LIMIT 1
  Refinery::User Exists (0.1ms)  SELECT 1 AS one FROM "refinery_users" WHERE "refinery_users"."email" = 'andrew@email.com' LIMIT 1
  Refinery::User Exists (0.1ms)  SELECT 1 AS one FROM "refinery_users" WHERE "refinery_users"."username" = 'andrew' LIMIT 1
   (0.0ms)  begin transaction
  CACHE (0.0ms)  SELECT "refinery_users".* FROM "refinery_users" WHERE ("slug" = 'andrew' OR "slug" LIKE 'andrew--%'ESCAPE '\') ORDER BY LENGTH("slug") DESC, "slug" DESC LIMIT 1
  CACHE (0.0ms)  SELECT 1 AS one FROM "refinery_users" WHERE "refinery_users"."email" = 'andrew@email.com' LIMIT 1
  CACHE (0.0ms)  SELECT 1 AS one FROM "refinery_users" WHERE "refinery_users"."username" = 'andrew' LIMIT 1
Binary data inserted for `string` type on column `encrypted_password`
  SQL (3.0ms)  INSERT INTO "refinery_users" ("created_at", "current_sign_in_at", "current_sign_in_ip", "email", "encrypted_password", "last_sign_in_at", "last_sign_in_ip", "remember_created_at", "reset_password_sent_at", "reset_password_token", "sign_in_count", "slug", "updated_at", "username") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)  [["created_at", Mon, 20 Jul 2015 23:49:56 UTC +00:00], ["current_sign_in_at", nil], ["current_sign_in_ip", nil], ["email", "andrew@email.com"], ["encrypted_password", "$2a$10$U8OwT6nJQQvIHP6dtMlzb.7D07S1M6Rt30HiKQ.E/RGrgbWWvBaTG"], ["last_sign_in_at", nil], ["last_sign_in_ip", nil], ["remember_created_at", nil], ["reset_password_sent_at", nil], ["reset_password_token", nil], ["sign_in_count", nil], ["slug", "andrew"], ["updated_at", Mon, 20 Jul 2015 23:49:56 UTC +00:00], ["username", "andrew"]]
  Refinery::User Load (0.1ms)  SELECT "refinery_users".* FROM "refinery_users" ORDER BY "refinery_users"."id" ASC LIMIT 500
   (0.6ms)  commit transaction
  Refinery::Role Load (0.2ms)  SELECT "refinery_roles".* FROM "refinery_roles" INNER JOIN "refinery_roles_users" ON "refinery_roles"."id" = "refinery_roles_users"."role_id" WHERE "refinery_roles_users"."user_id" = 1
  Refinery::Role Load (0.1ms)  SELECT "refinery_roles".* FROM "refinery_roles" WHERE "refinery_roles"."title" = 'Refinery' LIMIT 1
   (0.0ms)  begin transaction
   (0.3ms)  INSERT INTO "refinery_roles_users" ("user_id", "role_id") VALUES (1, 1)
   (0.6ms)  commit transaction
  Refinery::Role Load (0.2ms)  SELECT "refinery_roles".* FROM "refinery_roles" WHERE "refinery_roles"."title" = 'Refinery' LIMIT 1
   (0.1ms)  SELECT COUNT(*) FROM "refinery_users" INNER JOIN "refinery_roles_users" ON "refinery_users"."id" = "refinery_roles_users"."user_id" WHERE "refinery_roles_users"."role_id" = 1
  Refinery::Role Load (0.1ms)  SELECT "refinery_roles".* FROM "refinery_roles" WHERE "refinery_roles"."title" = 'Superuser' LIMIT 1
   (0.0ms)  begin transaction
  Refinery::Role Exists (0.1ms)  SELECT 1 AS one FROM "refinery_roles" WHERE "refinery_roles"."title" = 'Superuser' LIMIT 1
  SQL (0.3ms)  INSERT INTO "refinery_roles" ("title") VALUES (?)  [["title", "Superuser"]]
   (0.5ms)  commit transaction
   (0.0ms)  begin transaction
   (0.2ms)  INSERT INTO "refinery_roles_users" ("user_id", "role_id") VALUES (1, 2)
   (0.5ms)  commit transaction
Completed 500 Internal Server Error in 153.8ms

NoMethodError (undefined method `name' for nil:NilClass):
  activerecord (3.2.15) lib/active_record/associations/has_many_association.rb:58:in `cached_counter_attribute_name'
  activerecord (3.2.15) lib/active_record/associations/has_many_association.rb:54:in `has_cached_counter?'
  activerecord (3.2.15) lib/active_record/associations/has_many_association.rb:37:in `count_records'
  activerecord (3.2.15) lib/active_record/associations/collection_association.rb:261:in `size'
  activerecord (3.2.15) lib/active_record/associations/collection_association.rb:280:in `empty?'
  activerecord (3.2.15) lib/active_record/associations/collection_proxy.rb:46:in `empty?'
  refinerycms-authentication (2.1.5) app/models/refinery/user.rb:44:in `plugins='
  refinerycms-authentication (2.1.5) app/models/refinery/user.rb:99:in `create_first'
  refinerycms-authentication (2.1.5) app/controllers/refinery/users_controller.rb:18:in `create'
  actionpack (3.2.15) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.15) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.15) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.15) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (3.2.15) lib/active_support/callbacks.rb:458:in `_run__276420617275864787__process_action__1863765252319729218__callbacks'
  activesupport (3.2.15) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.15) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.15) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.15) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.15) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.15) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.15) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.15) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.15) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.15) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.15) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.15) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.15) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.15) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.15) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.15) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.15) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.15) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.15) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.15) lib/action_dispatch/routing/route_set.rb:36:in `call'
  actionpack (3.2.15) lib/action_dispatch/routing/mapper.rb:43:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.15) lib/action_dispatch/routing/route_set.rb:608:in `call'
  railties (3.2.15) lib/rails/engine.rb:484:in `call'
  railties (3.2.15) lib/rails/railtie/configurable.rb:30:in `method_missing'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.15) lib/action_dispatch/routing/route_set.rb:608:in `call'
  dragonfly (0.9.15) lib/dragonfly/middleware.rb:13:in `call'
  dragonfly (0.9.15) lib/dragonfly/middleware.rb:13:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `catch'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  actionpack (3.2.15) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.7) lib/rack/etag.rb:23:in `call'
  rack (1.4.7) lib/rack/conditionalget.rb:35:in `call'
  actionpack (3.2.15) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.15) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.15) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.7) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.7) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.15) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  dragonfly (0.9.15) lib/dragonfly/cookie_monster.rb:9:in `call'
  activerecord (3.2.15) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.15) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.15) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.15) lib/active_support/callbacks.rb:405:in `_run__3607125800161897472__call__2396009565521140805__callbacks'
  activesupport (3.2.15) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.15) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.15) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.15) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.15) lib/action_dispatch/middleware/reloader.rb:65:in `call'
  actionpack (3.2.15) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.15) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.15) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.15) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.15) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.15) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.15) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.15) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.7) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.7) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.15) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.7) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.15) lib/action_dispatch/middleware/static.rb:63:in `call'
  railties (3.2.15) lib/rails/engine.rb:484:in `call'
  railties (3.2.15) lib/rails/application.rb:231:in `call'
  rack (1.4.7) lib/rack/content_length.rb:14:in `call'
  railties (3.2.15) lib/rails/rack/log_tailer.rb:17:in `call'
  rack (1.4.7) lib/rack/handler/webrick.rb:59:in `service'
  /Users/andrew/.rbenv/versions/2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  /Users/andrew/.rbenv/versions/2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
  /Users/andrew/.rbenv/versions/2.2.2/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'


  Rendered /Users/andrew/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-3.2.15/lib/action_dispatch/middleware/templates/rescues/_trace.erb (1.1ms)
  Rendered /Users/andrew/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-3.2.15/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (1.1ms)
  Rendered /Users/andrew/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-3.2.15/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (20.9ms)
```

Here is my Gemfile and Gemfile.lock

```ruby
source 'https://rubygems.org'

gem 'rails', '3.2.15'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

group :development, :test do
  gem 'sqlite3'
end


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'

# Refinery CMS
gem 'refinerycms', '~> 2.1.0'

# Optionally, specify additional Refinery CMS Extensions here:
gem 'refinerycms-acts-as-indexed', '~> 1.0.0'
#  gem 'refinerycms-blog', '~> 2.1.0'
#  gem 'refinerycms-inquiries', '~> 2.1.0'
#  gem 'refinerycms-search', '~> 2.1.0'
#  gem 'refinerycms-page-images', '~> 2.1.0'
```

```
GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (3.2.15)
      actionpack (= 3.2.15)
      mail (~> 2.5.4)
    actionpack (3.2.15)
      activemodel (= 3.2.15)
      activesupport (= 3.2.15)
      builder (~> 3.0.0)
      erubis (~> 2.7.0)
      journey (~> 1.0.4)
      rack (~> 1.4.5)
      rack-cache (~> 1.2)
      rack-test (~> 0.6.1)
      sprockets (~> 2.2.1)
    activemodel (3.2.15)
      activesupport (= 3.2.15)
      builder (~> 3.0.0)
    activerecord (3.2.15)
      activemodel (= 3.2.15)
      activesupport (= 3.2.15)
      arel (~> 3.0.2)
      tzinfo (~> 0.3.29)
    activeresource (3.2.15)
      activemodel (= 3.2.15)
      activesupport (= 3.2.15)
    activesupport (3.2.15)
      i18n (~> 0.6, >= 0.6.4)
      multi_json (~> 1.0)
    acts_as_indexed (0.8.3)
    arel (3.0.3)
    awesome_nested_set (2.1.6)
      activerecord (>= 3.0.0)
    babosa (1.0.2)
    bcrypt (3.1.10)
    bcrypt-ruby (3.1.5)
      bcrypt (>= 3.1.3)
    builder (3.0.4)
    coffee-rails (3.2.2)
      coffee-script (>= 2.2.0)
      railties (~> 3.2.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.9.1.1)
    decorators (1.0.5)
      railties (>= 3.0.19)
    devise (2.2.8)
      bcrypt-ruby (~> 3.0)
      orm_adapter (~> 0.1)
      railties (~> 3.1)
      warden (~> 1.2.1)
    dragonfly (0.9.15)
      multi_json (~> 1.0)
      rack
    erubis (2.7.0)
    execjs (2.5.2)
    friendly_id (4.0.10.1)
      activerecord (>= 3.0, < 4.0)
    globalize (3.1.0)
      activemodel (>= 3.1.0, < 4.0.0)
      activerecord (>= 3.1.0, < 4.0.0)
    hike (1.2.3)
    i18n (0.7.0)
    journey (1.0.4)
    jquery-rails (2.3.0)
      railties (>= 3.0, < 5.0)
      thor (>= 0.14, < 2.0)
    json (1.8.3)
    mail (2.5.4)
      mime-types (~> 1.16)
      treetop (~> 1.4.8)
    mime-types (1.25.1)
    multi_json (1.11.2)
    orm_adapter (0.5.0)
    polyglot (0.3.5)
    rack (1.4.7)
    rack-cache (1.2)
      rack (>= 0.4)
    rack-ssl (1.3.4)
      rack
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (3.2.15)
      actionmailer (= 3.2.15)
      actionpack (= 3.2.15)
      activerecord (= 3.2.15)
      activeresource (= 3.2.15)
      activesupport (= 3.2.15)
      bundler (~> 1.0)
      railties (= 3.2.15)
    rails-i18n (0.7.4)
      i18n (~> 0.5)
    railties (3.2.15)
      actionpack (= 3.2.15)
      activesupport (= 3.2.15)
      rack-ssl (~> 1.3.2)
      rake (>= 0.8.7)
      rdoc (~> 3.4)
      thor (>= 0.14.6, < 2.0)
    rake (10.4.2)
    rdoc (3.12.2)
      json (~> 1.4)
    refinerycms (2.1.5)
      bundler (>= 1.2.2, < 2.0)
      refinerycms-authentication (= 2.1.5)
      refinerycms-core (= 2.1.5)
      refinerycms-dashboard (= 2.1.5)
      refinerycms-images (= 2.1.5)
      refinerycms-pages (= 2.1.5)
      refinerycms-resources (= 2.1.5)
    refinerycms-acts-as-indexed (1.0.0)
      acts_as_indexed (~> 0.8.0)
      refinerycms-core (~> 2.1.0)
    refinerycms-authentication (2.1.5)
      actionmailer (>= 3.1.11, < 3.3, != 3.2.9, != 3.2.8, != 3.2.7, != 3.2.6, != 3.2.5, != 3.2.4, != 3.2.3, != 3.2.2, != 3.2.11, != 3.2.10, != 3.2.1, != 3.2.0)
      devise (~> 2.2.3)
      refinerycms-core (= 2.1.5)
    refinerycms-core (2.1.5)
      actionpack (>= 3.1.11, < 3.3, != 3.2.9, != 3.2.8, != 3.2.7, != 3.2.6, != 3.2.5, != 3.2.4, != 3.2.3, != 3.2.2, != 3.2.11, != 3.2.10, != 3.2.1, != 3.2.0)
      activerecord (>= 3.1.11, < 3.3, != 3.2.9, != 3.2.8, != 3.2.7, != 3.2.6, != 3.2.5, != 3.2.4, != 3.2.3, != 3.2.2, != 3.2.11, != 3.2.10, != 3.2.1, != 3.2.0)
      awesome_nested_set (~> 2.1.3)
      decorators (~> 1.0.0)
      jquery-rails (~> 2.3.0)
      railties (>= 3.1.11, < 3.3, != 3.2.9, != 3.2.8, != 3.2.7, != 3.2.6, != 3.2.5, != 3.2.4, != 3.2.3, != 3.2.2, != 3.2.11, != 3.2.10, != 3.2.1, != 3.2.0)
      refinerycms-i18n (~> 2.1.0)
      sass-rails (~> 3.2.3)
      truncate_html (~> 0.9)
      will_paginate (~> 3.0.2)
    refinerycms-dashboard (2.1.5)
      refinerycms-core (= 2.1.5)
    refinerycms-i18n (2.1.0)
      rails-i18n (~> 0.7.3)
      routing-filter (~> 0.3.0)
    refinerycms-images (2.1.5)
      dragonfly (~> 0.9.14)
      refinerycms-core (= 2.1.5)
    refinerycms-pages (2.1.5)
      awesome_nested_set (~> 2.1.3)
      babosa (!= 0.3.6)
      friendly_id (~> 4.0.9)
      globalize (~> 3.1.0)
      refinerycms-core (= 2.1.5)
      seo_meta (~> 1.4.0)
    refinerycms-resources (2.1.5)
      acts_as_indexed (~> 0.8.0)
      dragonfly (~> 0.9.12)
      refinerycms-core (= 2.1.5)
    routing-filter (0.3.1)
      actionpack
    sass (3.4.16)
    sass-rails (3.2.6)
      railties (~> 3.2.0)
      sass (>= 3.1.10)
      tilt (~> 1.3)
    seo_meta (1.4.0)
      railties (>= 3.0.0)
    sprockets (2.2.3)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sqlite3 (1.3.10)
    thor (0.19.1)
    tilt (1.4.1)
    treetop (1.4.15)
      polyglot
      polyglot (>= 0.3.1)
    truncate_html (0.9.3)
    tzinfo (0.3.44)
    uglifier (2.7.1)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    warden (1.2.3)
      rack (>= 1.0)
    will_paginate (3.0.7)

PLATFORMS
  ruby

DEPENDENCIES
  coffee-rails (~> 3.2.1)
  jquery-rails
  rails (= 3.2.15)
  refinerycms (~> 2.1.0)
  refinerycms-acts-as-indexed (~> 1.0.0)
  sass-rails (~> 3.2.3)
  sqlite3
  uglifier (>= 1.0.3)

BUNDLED WITH
   1.10.5
```

**Comment by Hermanverschooten** [comment]
I can confirm this error. I setup refinerycms just now and get the same error trying to create the first user.
Site was created using the cli-command: refinerycms <sitename>. I am also using ruby 2.2.2.

**Comment by bricesanchez** [comment]
Refinery CMS 2.1 is deprecated, please use 3.0 or send us a pull request to fix this issue. Thanks.
