### ISSUE TITLE
Undefined method has_plugin? for Refinery::Authentication::Devise::User

### ISSUE THREAD

**Issue by andrewhavens** [refinery/refinerycms#3026]
I went to the images tab, uploaded some images, navigated to the page that I wanted to add the image....when the select image modal popped up, it displayed a 500 error. When I viewed the logs, this is what I found:

```
I, [2015-08-02T16:38:47.844508 #24328]  INFO -- : Started GET "/admin/images/insert?modal=true&visual_editor=true" for 73.164.205.208 at 2015-08-02 16:38:47 -0400
I, [2015-08-02T16:38:47.847589 #24328]  INFO -- : Processing by Refinery::Admin::ImagesController#insert as HTML
I, [2015-08-02T16:38:47.847766 #24328]  INFO -- :   Parameters: {"modal"=>"true", "visual_editor"=>"true", "locale"=>:en}
D, [2015-08-02T16:38:47.850393 #24328] DEBUG -- :   Refinery::Authentication::Devise::User Load (0.4ms)  SELECT  "refinery_authentication_devise_users".* FROM "refinery_authentication_devise_users" WHERE "refinery_authentication_devise_users"."id" = $1  ORDER BY "refinery_authentication_devise_users"."id" ASC LIMIT 1  [["id", 1]]
D, [2015-08-02T16:38:47.853353 #24328] DEBUG -- :   Refinery::Authentication::Devise::Role Load (0.4ms)  SELECT "refinery_authentication_devise_roles".* FROM "refinery_authentication_devise_roles" INNER JOIN "refinery_authentication_devise_roles_users" ON "refinery_authentication_devise_roles"."id" = "refinery_authentication_devise_roles_users"."role_id" WHERE "refinery_authentication_devise_roles_users"."user_id" = $1  [["user_id", 1]]
I, [2015-08-02T16:38:47.874876 #24328]  INFO -- :   Rendered /var/www/myapp/shared/bundle/ruby/2.2.0/bundler/gems/refinerycms-9253deaefe73/images/app/views/refinery/admin/images/insert.html.erb within layouts/refinery/admin_dialog (9.0ms)
I, [2015-08-02T16:38:47.875503 #24328]  INFO -- : Completed 500 Internal Server Error in 27ms (ActiveRecord: 0.8ms)
F, [2015-08-02T16:38:47.879564 #24328] FATAL -- :
ActionView::Template::Error (undefined method `has_plugin?' for #<Refinery::Authentication::Devise::User:0x007f599dce08d0>):
    1: <% user_can_modify_images = current_refinery_user.has_plugin?('refinery_images') %>
    2: <div id="dialog_menu_left">
    3:   <% if (any_images = @images.any?) or searching? %>
    4:     <span id="existing_image_radio" class="radio<%= ' selected_radio' if (no_errors = @image.errors.empty?) %>">
  activemodel (4.2.3) lib/active_model/attribute_methods.rb:433:in `method_missing'
  /var/www/myapp/shared/bundle/ruby/2.2.0/bundler/gems/refinerycms-9253deaefe73/images/app/views/refinery/admin/images/insert.html.erb:1:in `__var_www_myapp_shared_bundle_ruby_______bundler_gems_refinerycms_____deaefe___images_app_views_refinery_admin_images_insert_html_erb__4426575834752295040_70011432176220'
  actionview (4.2.3) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.3) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.3) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.3) lib/action_view/template.rb:143:in `render'
  actionview (4.2.3) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
  actionview (4.2.3) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.3) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.3) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.3) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.3) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.3) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
  actionview (4.2.3) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
  actionview (4.2.3) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (4.2.3) lib/action_view/renderer/template_renderer.rb:14:in `render'
  actionview (4.2.3) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.2.3) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.2.3) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.3) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.3) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.3) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.3) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.3) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.3) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (4.2.3) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /home/rails/.rbenv/versions/2.2.2/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
  activesupport (4.2.3) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (4.2.3) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:43:in `render'
  /var/www/myapp/shared/bundle/ruby/2.2.0/bundler/gems/refinerycms-9253deaefe73/images/app/controllers/refinery/admin/images_controller.rb:34:in `insert'
  actionpack (4.2.3) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.3) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.3) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.3) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.3) lib/active_support/callbacks.rb:115:in `call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:115:in `call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:553:in `block (2 levels) in compile'
  activesupport (4.2.3) lib/active_support/callbacks.rb:503:in `call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:503:in `call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:88:in `run_callbacks'
  actionpack (4.2.3) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.3) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.3) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.3) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.3) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.3) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.3) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.3) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.3) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.3) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.3) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.3) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:76:in `call'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:45:in `serve'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:821:in `call'
  railties (4.2.3) lib/rails/engine.rb:518:in `call'
  railties (4.2.3) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.3) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.2.3) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:821:in `call'
  dragonfly (1.0.10) lib/dragonfly/middleware.rb:14:in `call'
  dragonfly (1.0.10) lib/dragonfly/middleware.rb:14:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `catch'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.3) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:84:in `run_callbacks'
  actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.3) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.3) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.3) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  dragonfly (1.0.10) lib/dragonfly/cookie_monster.rb:9:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.3) lib/rails/engine.rb:518:in `call'
  railties (4.2.3) lib/rails/application.rb:165:in `call'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:94:in `process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception'
```

**Comment by andrewhavens** [comment]
Oops, just found this is a duplicate of https://github.com/refinery/refinerycms-authentication-devise/issues/10
