### ISSUE TITLE
Some of the specs are failing. 

### ISSUE THREAD

**Issue by AjayBarot-BTC** [refinery/refinerycms#3198]
`bundle exec rake`
```
Failures:

  1) Resources new/create uploads file
     Failure/Error: expect(page).to have_content("Refinery Is Awesome")
       expected to find text "Refinery Is Awesome" in "Company Name PAGES FILES IMAGES Switch to your website Refinery CMS™ Company Name There are no files yet. Click \"Upload new file\" to add your first file. Upload new file Upload new file"
     # ./resources/spec/features/refinery/admin/resources_spec.rb:35:in `block (3 levels) in <module:Admin>'
     # ./core/spec/support/database_cleaner.rb:18:in `block (2 levels) in <top (required)>'

  2) Page Visual Editor - Add Image When there is one image has behaviour: uploads images when the image type is acceptable the image is uploaded
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
       expected #count to have changed by 1, but was changed by 0
     Shared Example Group: "uploads images" called from ./images/spec/features/refinery/admin/images_spec.rb:60
     # ./images/spec/support/shared_examples/image_uploader.rb:24:in `block (3 levels) in <top (required)>'
     # ./core/spec/support/database_cleaner.rb:18:in `block (2 levels) in <top (required)>'

  3) Page Visual Editor - Add Image When there is one image has behaviour: uploads images when the image type is not acceptable the image is rejected
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
       expected to find text "Your image must be either a JPG, PNG or GIF" in "Library Upload There were problems with the following fields: You must specify an image for upload The maximum image size is 5 MB. Title Alt"
     Shared Example Group: "uploads images" called from ./images/spec/features/refinery/admin/images_spec.rb:60
     # ./images/spec/support/shared_examples/image_uploader.rb:33:in `block (4 levels) in <top (required)>'
     # ./images/spec/support/shared_examples/image_uploader.rb:32:in `block (3 levels) in <top (required)>'
     # ./core/spec/support/database_cleaner.rb:18:in `block (2 levels) in <top (required)>'

  4) Page Visual Editor - Add Image When there are no images has behaviour: uploads images when the image type is not acceptable the image is rejected
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
       expected to find text "Your image must be either a JPG, PNG or GIF" in "Upload There were problems with the following fields: You must specify an image for upload The maximum image size is 5 MB. Title Alt"
     Shared Example Group: "uploads images" called from ./images/spec/features/refinery/admin/images_spec.rb:52
     # ./images/spec/support/shared_examples/image_uploader.rb:33:in `block (4 levels) in <top (required)>'
     # ./images/spec/support/shared_examples/image_uploader.rb:32:in `block (3 levels) in <top (required)>'
     # ./core/spec/support/database_cleaner.rb:18:in `block (2 levels) in <top (required)>'

  5) Page Visual Editor - Add Image When there are no images has behaviour: uploads images when the image type is acceptable the image is uploaded
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
       expected #count to have changed by 1, but was changed by 0
     Shared Example Group: "uploads images" called from ./images/spec/features/refinery/admin/images_spec.rb:52
     # ./images/spec/support/shared_examples/image_uploader.rb:24:in `block (3 levels) in <top (required)>'
     # ./core/spec/support/database_cleaner.rb:18:in `block (2 levels) in <top (required)>'

  6) Page Visual Editor - Add Image When there are many images has behaviour: uploads images when the image type is not acceptable the image is rejected
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
       expected to find text "Your image must be either a JPG, PNG or GIF" in "Library Upload There were problems with the following fields: You must specify an image for upload The maximum image size is 5 MB. Title Alt"
     Shared Example Group: "uploads images" called from ./images/spec/features/refinery/admin/images_spec.rb:69
     # ./images/spec/support/shared_examples/image_uploader.rb:33:in `block (4 levels) in <top (required)>'
     # ./images/spec/support/shared_examples/image_uploader.rb:32:in `block (3 levels) in <top (required)>'
     # ./core/spec/support/database_cleaner.rb:18:in `block (2 levels) in <top (required)>'

  7) Page Visual Editor - Add Image When there are many images has behaviour: uploads images when the image type is acceptable the image is uploaded
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
       expected #count to have changed by 1, but was changed by 0
     Shared Example Group: "uploads images" called from ./images/spec/features/refinery/admin/images_spec.rb:69
     # ./images/spec/support/shared_examples/image_uploader.rb:24:in `block (3 levels) in <top (required)>'
     # ./core/spec/support/database_cleaner.rb:18:in `block (2 levels) in <top (required)>'

  8) the Admin Images Tab When there are many images has behaviour: uploads images when the image type is acceptable the image is uploaded
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
       expected #count to have changed by 1, but was changed by 0
     Shared Example Group: "uploads images" called from ./images/spec/features/refinery/admin/images_spec.rb:39
     # ./images/spec/support/shared_examples/image_uploader.rb:24:in `block (3 levels) in <top (required)>'
     # ./core/spec/support/database_cleaner.rb:18:in `block (2 levels) in <top (required)>'

  9) the Admin Images Tab When there are many images has behaviour: uploads images when the image type is not acceptable the image is rejected
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
       expected to find text "Your image must be either a JPG, PNG or GIF" in "There were problems with the following fields: You must specify an image for upload The maximum image size is 5 MB. Title Alt"
     Shared Example Group: "uploads images" called from ./images/spec/features/refinery/admin/images_spec.rb:39
     # ./images/spec/support/shared_examples/image_uploader.rb:33:in `block (4 levels) in <top (required)>'
     # ./images/spec/support/shared_examples/image_uploader.rb:32:in `block (3 levels) in <top (required)>'
     # ./core/spec/support/database_cleaner.rb:18:in `block (2 levels) in <top (required)>'

  10) the Admin Images Tab When there is one image has behaviour: uploads images when the image type is not acceptable the image is rejected
      Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
        expected to find text "Your image must be either a JPG, PNG or GIF" in "There were problems with the following fields: You must specify an image for upload The maximum image size is 5 MB. Title Alt"
      Shared Example Group: "uploads images" called from ./images/spec/features/refinery/admin/images_spec.rb:27
      # ./images/spec/support/shared_examples/image_uploader.rb:33:in `block (4 levels) in <top (required)>'
      # ./images/spec/support/shared_examples/image_uploader.rb:32:in `block (3 levels) in <top (required)>'
      # ./core/spec/support/database_cleaner.rb:18:in `block (2 levels) in <top (required)>'

  11) the Admin Images Tab When there is one image has behaviour: uploads images when the image type is acceptable the image is uploaded
      Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
        expected #count to have changed by 1, but was changed by 0
      Shared Example Group: "uploads images" called from ./images/spec/features/refinery/admin/images_spec.rb:27
      # ./images/spec/support/shared_examples/image_uploader.rb:24:in `block (3 levels) in <top (required)>'
      # ./core/spec/support/database_cleaner.rb:18:in `block (2 levels) in <top (required)>'

  12) the Admin Images Tab When there are no images has behaviour: uploads images when the image type is acceptable the image is uploaded
      Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
        expected #count to have changed by 1, but was changed by 0
      Shared Example Group: "uploads images" called from ./images/spec/features/refinery/admin/images_spec.rb:16
      # ./images/spec/support/shared_examples/image_uploader.rb:24:in `block (3 levels) in <top (required)>'
      # ./core/spec/support/database_cleaner.rb:18:in `block (2 levels) in <top (required)>'

  13) the Admin Images Tab When there are no images has behaviour: uploads images when the image type is not acceptable the image is rejected
      Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
        expected to find text "Your image must be either a JPG, PNG or GIF" in "There were problems with the following fields: You must specify an image for upload The maximum image size is 5 MB. Title Alt"
      Shared Example Group: "uploads images" called from ./images/spec/features/refinery/admin/images_spec.rb:16
      # ./images/spec/support/shared_examples/image_uploader.rb:33:in `block (4 levels) in <top (required)>'
      # ./images/spec/support/shared_examples/image_uploader.rb:32:in `block (3 levels) in <top (required)>'
      # ./core/spec/support/database_cleaner.rb:18:in `block (2 levels) in <top (required)>'

Finished in 2 minutes 48.8 seconds (files took 2.53 seconds to load)
532 examples, 13 failures, 9 pending

Failed examples:

rspec ./resources/spec/features/refinery/admin/resources_spec.rb:23 # Resources new/create uploads file
rspec ./images/spec/features/refinery/admin/images_spec.rb[2:2:3:1:1] # Page Visual Editor - Add Image When there is one image has behaviour: uploads images when the image type is acceptable the image is uploaded
rspec ./images/spec/features/refinery/admin/images_spec.rb[2:2:3:2:1] # Page Visual Editor - Add Image When there is one image has behaviour: uploads images when the image type is not acceptable the image is rejected
rspec ./images/spec/features/refinery/admin/images_spec.rb[2:1:1:2:1] # Page Visual Editor - Add Image When there are no images has behaviour: uploads images when the image type is not acceptable the image is rejected
rspec ./images/spec/features/refinery/admin/images_spec.rb[2:1:1:1:1] # Page Visual Editor - Add Image When there are no images has behaviour: uploads images when the image type is acceptable the image is uploaded
rspec ./images/spec/features/refinery/admin/images_spec.rb[2:3:3:2:1] # Page Visual Editor - Add Image When there are many images has behaviour: uploads images when the image type is not acceptable the image is rejected
rspec ./images/spec/features/refinery/admin/images_spec.rb[2:3:3:1:1] # Page Visual Editor - Add Image When there are many images has behaviour: uploads images when the image type is acceptable the image is uploaded
rspec ./images/spec/features/refinery/admin/images_spec.rb[1:3:6:1:1] # the Admin Images Tab When there are many images has behaviour: uploads images when the image type is acceptable the image is uploaded
rspec ./images/spec/features/refinery/admin/images_spec.rb[1:3:6:2:1] # the Admin Images Tab When there are many images has behaviour: uploads images when the image type is not acceptable the image is rejected
rspec ./images/spec/features/refinery/admin/images_spec.rb[1:2:6:2:1] # the Admin Images Tab When there is one image has behaviour: uploads images when the image type is not acceptable the image is rejected
rspec ./images/spec/features/refinery/admin/images_spec.rb[1:2:6:1:1] # the Admin Images Tab When there is one image has behaviour: uploads images when the image type is acceptable the image is uploaded
rspec ./images/spec/features/refinery/admin/images_spec.rb[1:1:2:1:1] # the Admin Images Tab When there are no images has behaviour: uploads images when the image type is acceptable the image is uploaded
rspec ./images/spec/features/refinery/admin/images_spec.rb[1:1:2:2:1] # the Admin Images Tab When there are no images has behaviour: uploads images when the image type is not acceptable the image is rejected

```

**Comment by parndt** [comment]
@AjayBarot-BTC do you have ImageMagick installed? 😄

**Comment by AjayBarot-BTC** [comment]
@parndt : Yes I have ImageMagick Package installed in my machine. :relieved:

![image_magik](https://cloud.githubusercontent.com/assets/5164950/16017784/0d88f8d4-31bf-11e6-902e-5c905ddf81f6.png)

Thank you!

**Comment by parndt** [comment]
Which shell are you using? Bash? zsh?

**Comment by AjayBarot-BTC** [comment]
@parndt : I am using Bash

**Comment by parndt** [comment]
Do you have `phantomjs` installed?

Otherwise, I'm not entirely certain why these tests fail for you, but they're passing on CI and I can't make them fail locally.

**Comment by AjayBarot-BTC** [comment]
@parndt : Yes I have `phantomjs` version 2.1.1. Yeah I know that all test are passing on CI. anyway I will figure out the reason why tests are failing in my machine and let you know the details. Thanks

**Comment by bricesanchez** [comment]
What is your version of `bundler` ?

**Comment by AjayBarot-BTC** [comment]
@bricesanchez : Bundler version 1.11.2

**Comment by bricesanchez** [comment]
There was a problem with `bundler` between 1.12.0 -> 1.12.3 but it's not your case.

I don't know what happens on your machine, it does not fail locally for me too.
