### ISSUE TITLE
Issue in migrating database after adding refinerycms gem

### ISSUE THREAD

**Issue by PriyaBhatia** [refinery/refinerycms#3199]
I am integrating refinerycms in existing application and followed steps mentioned in http://www.refinerycms.com/guides/with-an-existing-rails-app 

My gemfile contains following:

gem 'refinerycms', github: 'refinery/refinerycms', branch: 'master'
gem 'refinerycms-i18n', github: 'refinery/refinerycms-i18n', branch: 'master'

(Adding gem 'refinerycms', '~> 3.0.0' to gemfile also generates same error)

Error==>  Mysql2::Error: Table 'refinery_base_model_translations' already exists: CREATE TABLE `refinery_base_model_translations` (`id` int(11) auto_increment PRIMARY KEY, `refinery_base_model_id` int(11) NOT NULL, `locale` varchar(255) NOT NULL, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL) ENGINE=InnoDB

**Comment by bricesanchez** [comment]
It looks like you already have the `refinery_base_model_translations` table in your database, Did you run  `rails generate refinery:cms --fresh-installation` multiple times ?

**Comment by PriyaBhatia** [comment]
@bricesanchez  Yes, because when first time I run this at that time also I got same error.
Then first I run rake db:drop and then run the rails g refinery:cms --fresh-installation command.

**Comment by PriyaBhatia** [comment]
Commenting out these lines in the migration:

     #::Refinery::PagePart.create_translation_table!({
     #  :body => :text
     #})
    #::Refinery::Page.create_translation_table!({
      #  :title => :string,
      #  :custom_slug => :string,
      #  :menu_title => :string,
      #  :slug => :string
     # })

and removed following whole migration 
AddCustomSlugToRefineryPages:
    
Fix issue of migrations, but now when I run rake db:seed get following error:

ActiveRecord::StatementInvalid: Mysql2::Error: Unknown column 'refinery_base_models.menu_match' in 'where clause': SELECT COUNT(*) FROM `refinery_base_models` WHERE `refinery_base_models`.`menu_match` = '^/$'

**Comment by bricesanchez** [comment]
Commenting out migrations is not a really great idea, do you have a backup of your database before adding refinerycms? it will probably easier to retrying the installation on a clean DB.

**Comment by bricesanchez** [comment]
Did you solved your problem ?

**Comment by PriyaBhatia** [comment]
No I am not able to fix this issue. Don't have backup of database but  I changed database name in database.yml file and started from scratch , it is not working for me.

**Comment by bricesanchez** [comment]
Weird, there is probably something missing. 
At this step, the best should be to write me a step by step to reproduce the problem or to grant me access to the app.

It will be easier for me to find the problem.

**Comment by PriyaBhatia** [comment]
Gems in gem file:

gem 'refinerycms', '~> 3.0.0'
gem 'refinerycms-page-images', '~> 3.0.0', github: "refinery/refinerycms-page-images", branch: "master"
gem 'refinerycms-wymeditor'

run bundle install
Rails version ==> 4.2.6

Then 
**rake db:create (new database)**

 **rails generate refinery:page_images**
        rake  refinery_page_images:install:migrations
Copied migration 20160622114805_create_page_images.refinery_page_images.rb from refinery_page_images
Copied migration 20160622114806_add_caption_to_image_pages.refinery_page_images.rb from refinery_page_images
Copied migration 20160622114807_translate_page_image_captions.refinery_page_images.rb from refinery_page_images
Copied migration 20160622114808_change_page_to_polymorphic.refinery_page_images.rb from refinery_page_images
      create  config/initializers/refinery/page_images.rb

Then run next 

 **rails generate refinery:pages**
        rake  refinery_pages:install:migrations
Copied migration 20160622114958_create_refinerycms_pages_schema.refinery_pages.rb from refinery_pages
Copied migration 20160622114959_add_custom_slug_to_refinery_pages.refinery_pages.rb from refinery_pages
Copied migration 20160622114960_add_slug_to_refinery_page_parts.refinery_pages.rb from refinery_pages
Copied migration 20160622114961_update_slug_and_title_in_refinery_page_parts.refinery_pages.rb from refinery_pages
Copied migration 20160622114962_fix_slug_format_in_refinery_page_parts.refinery_pages.rb from refinery_pages
      create  config/initializers/refinery/pages.rb
      append  db/seeds.rb

**And Finally rake db:migrate and got following**

== 20160622114805 CreatePageImages: migrating =================================
-- create_table("refinery_base_models", {:id=>false})
   -> 0.0778s
-- add_index("refinery_base_models", :image_id)
   -> 0.1665s
-- add_index("refinery_base_models", :page_id)
   -> 0.1178s
== 20160622114805 CreatePageImages: migrated (0.3937s) ========================

== 20160622114806 AddCaptionToImagePages: migrating ===========================
-- add_column("refinery_base_models", :caption, :text)
   -> 0.1336s
== 20160622114806 AddCaptionToImagePages: migrated (0.1338s) ==================

== 20160622114807 TranslatePageImageCaptions: migrating =======================
-- add_column("refinery_base_models", :id, :primary_key)
   -> 0.1519s
== 20160622114807 TranslatePageImageCaptions: migrated (0.6802s) ==============

== 20160622114808 ChangePageToPolymorphic: migrating ==========================
-- add_column("refinery_base_models", :page_type, :string, {:default=>"page"})
   -> 0.1537s
== 20160622114808 ChangePageToPolymorphic: migrated (0.1539s) =================

== 20160622114958 CreateRefinerycmsPagesSchema: migrating =====================
-- create_table(:refinery_page_parts)
   -> 0.0505s
-- add_index(:refinery_page_parts, :id)
   -> 0.1262s
-- add_index(:refinery_page_parts, :refinery_page_id)
   -> 0.1215s
-- create_table(:refinery_pages)
   -> 0.0767s
-- add_index(:refinery_pages, :depth)
   -> 0.1283s
-- add_index(:refinery_pages, :id)
   -> 0.1610s
-- add_index(:refinery_pages, :lft)
   -> 0.1198s
-- add_index(:refinery_pages, :parent_id)
   -> 0.1822s
-- add_index(:refinery_pages, :rgt)
   -> 0.1196s
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Table 'refinery_base_model_translations' already exists: CREATE TABLE `refinery_base_model_translations` (`id` int(11) auto_increment PRIMARY KEY, `refinery_base_model_id` int(11) NOT NULL, `locale` varchar(255) NOT NULL, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL) ENGINE=InnoDB
/home/nikhil/.rvm/gems/ruby-2.2.1@tracki94/gems/mysql2-0.3.21/lib/mysql2/client.rb:80:in `_query'
/home/nikhil/.rvm/gems/ruby-2.2.1@tracki94/gems/mysql2-0.3.21/lib/mysql2/client.rb:80:in `block in query'
/home/nikhil/.rvm/gems/ruby-2.2.1@tracki94/gems/mysql2-0.3.21/lib/mysql2/client.rb:79:in `handle_interrupt'

**Comment by bricesanchez** [comment]
Did you find a solution?

At this time the only problem i've seen is you run : `rails generate refinery:page_images` before `rails generate refinery:pages`. You should do the opposite.

**Comment by bricesanchez** [comment]
Closed due to no activity
