### ISSUE TITLE
  Bundler could not find compatible versions for gem "refinerycms-core"

### ISSUE THREAD

**Issue by iFurniture** [refinery/refinerycms#3239]
Hi everyone,

this is my issue, i don't know how to resolve it, i'm trying everything...

i cann't find where is defined the version of refinerycms..... i search in Gemfile and in refinerycms-productos.gemspec.

The log..
 ```
    Bundler could not find compatible versions for gem "refinerycms-core":

       In Gemfile:

       refinerycms was resolved to 4.0.0.dev, which depends on

       refinerycms-core (= 4.0.0.dev)

       

       refinerycms was resolved to 4.0.0.dev, which depends on

       refinerycms-core (= 4.0.0.dev)

       

       refinerycms was resolved to 4.0.0.dev, which depends on

       refinerycms-core (= 4.0.0.dev)

       

       refinerycms was resolved to 4.0.0.dev, which depends on

       refinerycms-core (= 4.0.0.dev)

       

       refinerycms-productos was resolved to 1.0, which depends on

       refinerycms-core (~> 3.0.0)

       

       refinerycms-productos was resolved to 1.0, which depends on

       refinerycms-core (~> 3.0.0)

       

       refinerycms-blog was resolved to 3.0.1, which depends on

       refinerycms-settings (~> 3.0.0) was resolved to 3.0.0, which depends on

       refinerycms-core (>= 3.0.0, ~> 3.0)

 !

 !     Failed to install gems via Bundler.

 !

 !     Push rejected, failed to compile Ruby app.

 !     Push failed


```

This is my Gemfile

```
`source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 4.2.4'
# Use sqlite3 as the database for Active Record
group :development, :test do
  gem 'sqlite3'
end
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'bourbon'
gem 'neat'
gem 'meta-tags', '~> 2.0.0'

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

group :production do
  gem 'pg'
  gem 'rails_12factor'
  gem 'dragonfly-s3_data_store'
end

group :staging do
  gem 'rails_12factor'
end

gem 'refinerycms', git: 'https://github.com/refinery/refinerycms', branch: 'master'

gem 'quiet_assets', group: :development

# Add support for searching inside Refinery's admin interface.
gem 'refinerycms-acts-as-indexed', ['~> 2.0', '>= 2.0.0']

# Add support for Refinery's custom fork of the visual editor WYMeditor.
gem 'refinerycms-wymeditor', ['~> 1.0', '>= 1.0.6']

# The default authentication adapter
gem 'refinerycms-authentication-devise', '~> 1.0'

gem 'mailchimp-api', require: 'mailchimp'
gem 'figaro'
gem 'refinerycms-blog', git: 'https://github.com/refinery/refinerycms-blog', branch: 'master'

gem 'refinerycms-productos', path: 'vendor/extensions'`

```
and this is the refinerycms-productos.gemspec

```
`# Encoding: UTF-8

Gem::Specification.new do |s|
  s.platform          = Gem::Platform::RUBY
  s.name              = 'refinerycms-productos'
  s.version           = '1.0'
  s.description       = 'Ruby on Rails Productos extension for Refinery CMS'
  s.date              = '2015-11-30'
  s.summary           = 'Productos extension for Refinery CMS'
  s.require_paths     = %w(lib)
  s.files             = Dir["{app,config,db,lib}/**/*"] + ["readme.md"]
  s.author            = 'DevAcademy'

  # Runtime dependencies
  s.add_dependency             'refinerycms-core', '~> 3.0', '>= 3.0.0'
  s.add_dependency             'acts_as_indexed',     '~> 0.8.0'

  # Development dependencies (usually used for testing)
  s.add_development_dependency 'refinerycms-testing', '~> 3.0.0'
end
`
```

I will watching for yours answers, thank you.

**Comment by bricesanchez** [comment]
Hi! 

At this time, you should use `3-0-stable` branch of refinerycms : 
```ruby
gem 'refinerycms', git: 'https://github.com/refinery/refinerycms', branch: '3-0-stable'
```

It will fix your dependency bug.

**Comment by iFurniture** [comment]
Thank you, that's awesome, solved my problem. @bricesanchez

**Comment by bricesanchez** [comment]
You're welcome!

**Comment by iFurniture** [comment]
Do you can solve a problem with the command "Rails server"?  i have now that problem :(

**Comment by bricesanchez** [comment]
Which problem ?

**Comment by iFurniture** [comment]
Here is the post whit the problem:

https://github.com/iFurniture/iFurniture/issues/1

**Comment by bricesanchez** [comment]
`bundle update` then `rails s` should fix your problem

**Comment by iFurniture** [comment]
No :c the issue continue.....

**Comment by bricesanchez** [comment]
```ruby
You have already activated activesupport 5.0.
0, but your Gemfile requires activesupport 4.2.7. Prepending `bundle exec` to yo
ur command may solve this. (Gem::LoadError)
```

So it's an ENV problem, did you try to run : `bundle exec rails s` ?

**Comment by iFurniture** [comment]
Yes, i got this...

```

C:\Sites\ifurniture>bundle exec rails s
Looks like your app's ./bin/rails is a stub that was generated by Bundler.

In Rails 4, your app's bin/ directory contains executables that are versioned
like any other source code, rather than stubs that are generated on demand.

Here's how to upgrade:

  bundle config --delete bin    # Turn off Bundler's stub generator
  rake rails:update:bin         # Use the new Rails 4 executables
  git add bin                   # Add bin/ to source control

You may need to remove bin/ from your .gitignore as well.

When you install a gem whose executable you want to use in your app,
generate it and add it to source control:

  bundle binstubs some-gem-name
  git add bin/new-executable

=> Booting WEBrick
=> Rails 4.2.7.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/dat
a_source.rb:182:in `rescue in create_default_data_source': No source of timezone
 data could be found. (TZInfo::DataSourceNotFound)
Please refer to http://tzinfo.github.io/datasourcenotfound for help resolving th
is error.
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/tzinfo-1.2.2/l
ib/tzinfo/data_source.rb:179:in `create_default_data_source'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/tzinfo-1.2.2/l
ib/tzinfo/data_source.rb:40:in `block in get'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/tzinfo-1.2.2/l
ib/tzinfo/data_source.rb:39:in `synchronize'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/tzinfo-1.2.2/l
ib/tzinfo/data_source.rb:39:in `get'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/tzinfo-1.2.2/l
ib/tzinfo/timezone.rb:629:in `data_source'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/tzinfo-1.2.2/l
ib/tzinfo/timezone.rb:92:in `get'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/tzinfo-1.2.2/l
ib/tzinfo/timezone_proxy.rb:67:in `real_timezone'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/tzinfo-1.2.2/l
ib/tzinfo/timezone_proxy.rb:30:in `period_for_utc'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/tzinfo-1.2.2/l
ib/tzinfo/timezone.rb:549:in `current_period'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-
4.2.7.1/lib/active_support/values/time_zone.rb:281:in `utc_offset'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-
4.2.7.1/lib/active_support/values/time_zone.rb:243:in `block in []'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-
4.2.7.1/lib/active_support/values/time_zone.rb:243:in `tap'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-
4.2.7.1/lib/active_support/values/time_zone.rb:243:in `[]'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-
4.2.7.1/lib/active_support/core_ext/time/zones.rb:61:in `find_zone!'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-
4.2.7.1/lib/active_support/railtie.rb:20:in `block in <class:Railtie>'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.7
.1/lib/rails/initializable.rb:30:in `instance_exec'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.7
.1/lib/rails/initializable.rb:30:in `run'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.7
.1/lib/rails/initializable.rb:55:in `block in run_initializers'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/tsort.rb:226:in `block i
n tsort_each'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/tsort.rb:348:in `block (
2 levels) in each_strongly_connected_component'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/tsort.rb:429:in `each_st
rongly_connected_component_from'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/tsort.rb:347:in `block i
n each_strongly_connected_component'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `call'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each_st
rongly_connected_component'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/tsort.rb:224:in `tsort_e
ach'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/tsort.rb:203:in `tsort_e
ach'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.7
.1/lib/rails/initializable.rb:54:in `run_initializers'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.7
.1/lib/rails/application.rb:352:in `initialize!'
        from C:/Sites/ifurniture/config/environment.rb:5:in `<top (required)>'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-
4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-
4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-
4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-
4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
        from C:/Sites/ifurniture/config.ru:3:in `block in <main>'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib
/rack/builder.rb:55:in `instance_eval'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib
/rack/builder.rb:55:in `initialize'
        from C:/Sites/ifurniture/config.ru:in `new'
        from C:/Sites/ifurniture/config.ru:in `<main>'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib
/rack/builder.rb:49:in `eval'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib
/rack/builder.rb:49:in `new_from_string'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib
/rack/builder.rb:40:in `parse_file'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib
/rack/server.rb:299:in `build_app_and_options_from_config'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib
/rack/server.rb:208:in `app'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.7
.1/lib/rails/commands/server.rb:61:in `app'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib
/rack/server.rb:336:in `wrapped_app'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.7
.1/lib/rails/commands/server.rb:139:in `log_to_stdout'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.7
.1/lib/rails/commands/server.rb:78:in `start'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.7
.1/lib/rails/commands/commands_tasks.rb:80:in `block in server'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.7
.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.7
.1/lib/rails/commands/commands_tasks.rb:75:in `server'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.7
.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.7
.1/lib/rails/commands.rb:17:in `<top (required)>'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.7
.1/lib/rails/app_rails_loader.rb:45:in `require'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.7
.1/lib/rails/app_rails_loader.rb:45:in `block in exec_app_rails'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.7
.1/lib/rails/app_rails_loader.rb:34:in `loop'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.7
.1/lib/rails/app_rails_loader.rb:34:in `exec_app_rails'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.7
.1/lib/rails/cli.rb:5:in `<top (required)>'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.7
.1/bin/rails:9:in `require'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.7
.1/bin/rails:9:in `<top (required)>'
        from C:/RailsInstaller/Ruby2.2.0/bin/rails:22:in `load'
        from C:/RailsInstaller/Ruby2.2.0/bin/rails:22:in `<main>'
```

**Comment by bricesanchez** [comment]
```
C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/dat
a_source.rb:182:in `rescue in create_default_data_source': No source of timezone
 data could be found. (TZInfo::DataSourceNotFound)
Please refer to http://tzinfo.github.io/datasourcenotfound for help resolving th
is error.
```

https://github.com/tzinfo/tzinfo/wiki/Resolving-TZInfo::DataSourceNotFound-Errors#using-tzinfo-data-with-bundler-or-ruby-on-rails

**Comment by iFurniture** [comment]
Aparently with the `bundle exec rails s` work, but to entry to localhost:3000 give me the error 404 page not found and when i deploy to heroku the app crash and not work.

**Comment by bricesanchez** [comment]
`localhost:3000` could give you a 404 error if you didn't seed the database with `bundle exec rake db:seed`.

If you want to deploy your app on heroku, you should follow this guide: http://www.refinerycms.com/guides/heroku

**Comment by iFurniture** [comment]
This is the log of the 404 not found...

Thanks for your help, please keep helping me.......

```
C:\Sites\ifurniture>bundle exec rails s
=> Booting WEBrick
=> Rails 4.2.7.1 application starting in 

development on http://localhost:3000
=> Run `rails server -h` for more startup 

options
=> Ctrl-C to shutdown server
[2016-08-12 11:47:28] INFO  WEBrick 1.3.1
[2016-08-12 11:47:28] INFO  ruby 2.2.4 (2015-

12-16) [i386-mingw32]
[2016-08-12 11:47:28] INFO  

WEBrick::HTTPServer#start: pid=4400 port=3000


Started GET "/" for ::1 at 2016-08-12 11:48:20 

-0500
  ActiveRecord::SchemaMigration Load (1.0ms)  

SELECT "schema_migrations".* FROM
"schema_migrations"
Processing by Refinery::PagesController#home 

as HTML
  Parameters: {"locale"=>:es}
  Refinery::Page Load (1.0ms)  SELECT  

"refinery_pages".* FROM "refinery_pages"
WHERE "refinery_pages"."link_url" = ? LIMIT 1  

[["link_url", "/"]]
  Refinery::Page Load (0.0ms)  SELECT  

"refinery_pages".* FROM "refinery_pages"
WHERE "refinery_pages"."menu_match" = ?  ORDER 

BY "refinery_pages"."id" ASC LIMI
T 1  [["menu_match", "^/404$"]]
  Rendered public/404.html (14.0ms)
Filter chain halted as :find_page rendered or 

redirected
Completed 404 Not Found in 5991ms (Views: 

4657.1ms | ActiveRecord: 2.0ms)


Started GET "/" for ::1 at 2016-08-12 11:48:38 

-0500
Processing by Refinery::PagesController#home 

as HTML
  Parameters: {"locale"=>:es}
  Refinery::Page Load (0.0ms)  SELECT  

"refinery_pages".* FROM "refinery_pages"
WHERE "refinery_pages"."link_url" = ? LIMIT 1  

[["link_url", "/"]]
  Refinery::Page Load (1.0ms)  SELECT  

"refinery_pages".* FROM "refinery_pages"
WHERE "refinery_pages"."menu_match" = ?  ORDER 

BY "refinery_pages"."id" ASC LIMI
T 1  [["menu_match", "^/404$"]]
  Rendered public/404.html (0.0ms)
Filter chain halted as :find_page rendered or 

redirected
Completed 404 Not Found in 5137ms (Views: 

3637.4ms | ActiveRecord: 1.0ms)


Started GET "/ikids" for ::1 at 2016-08-12 

11:53:11 -0500
Processing by Refinery::PagesController#show 

as HTML
  Parameters: {"path"=>"ikids", "locale"=>:es}
  Refinery::Page Load (1.0ms)  SELECT  

"refinery_pages".* FROM "refinery_pages"
INNER JOIN "refinery_page_translations" ON 

"refinery_page_translations"."refiner
y_page_id" = "refinery_pages"."id" WHERE 

"refinery_pages"."parent_id" IS NULL AN
D "refinery_page_translations"."locale" IN 

('es', 'en') AND "refinery_page_trans
lations"."slug" = 'ikids'  ORDER BY 

"refinery_pages"."id" ASC LIMIT 1
  Refinery::Page Load (0.0ms)  SELECT  

"refinery_pages".* FROM "refinery_pages"
WHERE "refinery_pages"."menu_match" = ?  ORDER 

BY "refinery_pages"."id" ASC LIMI
T 1  [["menu_match", "^/404$"]]
  Rendered public/404.html (0.0ms)
Filter chain halted as :find_page rendered or 

redirected
Completed 404 Not Found in 24836ms (Views: 

13000.4ms | ActiveRecord: 2.0ms)
[2016-08-12 11:59:26] INFO  going to shutdown 

...
[2016-08-12 11:59:27] INFO  

WEBrick::HTTPServer#start done.
Exiting

```
