### ISSUE TITLE
Cannot login on new site: Cannot redirect to nil!

### ISSUE THREAD

**Issue by soundasleep** [refinery/refinerycms#3290]
I created a brand new Refinery application:

```
rails new myapp -m http://refinerycms.com/t/3-0-stable
rails s
```

I could visit http://localhost:3000/refinery fine, and made my first user.

However when I logged out, I can no longer login because any request to /refinery after logging in - with either my old user or my new user - crashes with:

```
ActionController::ActionControllerError in Refinery::Admin::CoreController#index
Cannot redirect to nil!
```

The site is essentially dead now because I can't login at all. Clearing cookies didn't help.

Stack trace:

```
actionpack (4.2.8) lib/action_controller/metal/redirecting.rb:70:in `redirect_to'
actionpack (4.2.8) lib/action_controller/metal/flash.rb:57:in `redirect_to'
actionpack (4.2.8) lib/action_controller/metal/instrumentation.rb:64:in `block in redirect_to'
activesupport (4.2.8) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.8) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.8) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.8) lib/action_controller/metal/instrumentation.rb:63:in `redirect_to'
turbolinks (5.0.1) lib/turbolinks/redirection.rb:12:in `redirect_to'
refinerycms-core (3.0.5) app/controllers/refinery/admin/core_controller.rb:5:in `index'
actionpack (4.2.8) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.2.8) lib/abstract_controller/base.rb:198:in `process_action'
actionpack (4.2.8) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.2.8) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
```

Versions:

```
$ ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
$ rails -v
Rails 4.2.8
```

**Comment by bricesanchez** [comment]
Did you find a solution?
