### ISSUE TITLE
Extension generators produce migrations missing version

### ISSUE THREAD

**Issue by sfcgeorge** [refinery/refinerycms#3312]
Rails (5?) requires migrations to specify the minimum version of Rails the migration was written for  otherwise it raises an error. Manually adding this version constraint before copying and running the migrations works fine.

```
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateVideosVideos < ActiveRecord::Migration[4.2]
/path/site/db/migrate/20170917165814_create_videos_videos.refinery_videos.rb:2:in `<top (required)>'
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateVideosVideos < ActiveRecord::Migration[4.2]
/path/site/db/migrate/20170917165814_create_videos_videos.refinery_videos.rb:2:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by bricesanchez** [comment]
You're right, we have to update this file : https://github.com/refinery/refinerycms/blob/2c3b7c31314cc3fbcd425d7c461e14002bfda7fc/core/lib/generators/refinery/engine/templates/db/migrate/1_create_namespace_plural_name.rb.erb

Could you open a pull request?

**Comment by sfcgeorge** [comment]
Sure
