### ISSUE TITLE
I want to add refinery:blog in my App. ,but  occur error!

### ISSUE THREAD

**Issue by iiewad** [refinery/refinerycms#3344]
```
➜  PDFReaderPro_Server git:(dw-develop) ✗ rails generate refinery:cms
Running via Spring preloader in process 2935
-- You may need to remove 'app/views/layouts/application.html.erb' for Refinery to function properly --
        gsub  Gemfile
      append  .gitignore
   identical  config/database.yml.mysql
   identical  config/database.yml.postgresql
   identical  config/database.yml.sqlite3
   identical  app/decorators/controllers/refinery/.keep
   identical  app/decorators/models/refinery/.keep
        rake  railties:install:migrations db:create db:migrate db:seed
Database 'pdf-reader-dev' already exists
Database 'pdf-reader-test' already exists
== 20180207072628 AddSourceUrlToBlogPosts: migrating ==========================
== 20180207072628 AddSourceUrlToBlogPosts: migrated (0.0000s) =================

== 20180207072629 AddAccessCountToPosts: migrating ============================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `translates' for #<Class:0x007ffe17e390a0>
Did you mean?  transaction
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/bundler/gems/refinerycms-blog-621c0f2c1975/app/models/refinery/blog/post.rb:9:in `<class:Post>'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/bundler/gems/refinerycms-blog-621c0f2c1975/app/models/refinery/blog/post.rb:6:in `<module:Blog>'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/bundler/gems/refinerycms-blog-621c0f2c1975/app/models/refinery/blog/post.rb:5:in `<module:Refinery>'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/bundler/gems/refinerycms-blog-621c0f2c1975/app/models/refinery/blog/post.rb:4:in `<top (required)>'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1@global/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:476:in `load'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1@global/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:476:in `block in load_file'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1@global/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:661:in `new_constants_in'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1@global/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:475:in `load_file'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1@global/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:374:in `block in require_or_load'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1@global/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:36:in `block in load_interlock'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1@global/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1@global/gems/activesupport-5.1.4/lib/active_support/concurrency/share_lock.rb:149:in `exclusive'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1@global/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:11:in `loading'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1@global/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:36:in `load_interlock'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1@global/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:357:in `require_or_load'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1@global/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:510:in `load_missing_constant'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1@global/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:202:in `const_missing'
/Users/kdanmobile/ror_workspace/PDFReaderPro_Server/db/migrate/20180207072629_add_access_count_to_posts.refinery_blog.rb:4:in `change'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/migration.rb:792:in `exec_migration'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/migration.rb:776:in `block (2 levels) in migrate'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/migration.rb:775:in `block in migrate'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:408:in `with_connection'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/migration.rb:774:in `migrate'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/migration.rb:953:in `migrate'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/migration.rb:1230:in `block in execute_migration_in_transaction'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/migration.rb:1298:in `block in ddl_transaction'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/transactions.rb:210:in `transaction'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/migration.rb:1298:in `ddl_transaction'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `each'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `migrate_without_lock'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/migration.rb:1148:in `block in migrate'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/migration.rb:1317:in `with_advisory_lock'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/migration.rb:1148:in `migrate'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/migration.rb:1007:in `up'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/migration.rb:985:in `migrate'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'

Caused by:
NoMethodError: undefined method `translates' for #<Class:0x007ffe17e390a0>
Did you mean?  transaction
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/bundler/gems/refinerycms-blog-621c0f2c1975/app/models/refinery/blog/post.rb:9:in `<class:Post>'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/bundler/gems/refinerycms-blog-621c0f2c1975/app/models/refinery/blog/post.rb:6:in `<module:Blog>'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/bundler/gems/refinerycms-blog-621c0f2c1975/app/models/refinery/blog/post.rb:5:in `<module:Refinery>'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/bundler/gems/refinerycms-blog-621c0f2c1975/app/models/refinery/blog/post.rb:4:in `<top (required)>'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1@global/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:476:in `load'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1@global/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:476:in `block in load_file'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1@global/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:661:in `new_constants_in'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1@global/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:475:in `load_file'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1@global/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:374:in `block in require_or_load'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1@global/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:36:in `block in load_interlock'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1@global/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1@global/gems/activesupport-5.1.4/lib/active_support/concurrency/share_lock.rb:149:in `exclusive'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1@global/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:11:in `loading'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1@global/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:36:in `load_interlock'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1@global/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:357:in `require_or_load'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1@global/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:510:in `load_missing_constant'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1@global/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:202:in `const_missing'
/Users/kdanmobile/ror_workspace/PDFReaderPro_Server/db/migrate/20180207072629_add_access_count_to_posts.refinery_blog.rb:4:in `change'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/migration.rb:792:in `exec_migration'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/migration.rb:776:in `block (2 levels) in migrate'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/migration.rb:775:in `block in migrate'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:408:in `with_connection'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/migration.rb:774:in `migrate'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/migration.rb:953:in `migrate'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/migration.rb:1230:in `block in execute_migration_in_transaction'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/migration.rb:1298:in `block in ddl_transaction'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/transactions.rb:210:in `transaction'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/migration.rb:1298:in `ddl_transaction'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `each'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `migrate_without_lock'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/migration.rb:1148:in `block in migrate'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/migration.rb:1317:in `with_advisory_lock'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/migration.rb:1148:in `migrate'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/migration.rb:1007:in `up'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/migration.rb:985:in `migrate'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/Users/kdanmobile/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

My GemFile:
```
  1 source 'https://rubygems.org'
  2
  3 git_source(:github) do |repo_name|
  4   repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  5   "https://github.com/#{repo_name}.git"
  6 end
  7
  8
  9 gem 'rails', '~> 5.1.0'
 10 gem 'pg', '~> 0.18'
 11 gem 'puma', '~> 3.7'
 12 gem 'sass-rails', '~> 5.0'
 13 gem 'bootstrap-sass', '~> 3.3.7'
 14 gem 'jquery-rails'
 15
 16 gem 'uglifier', '>= 1.3.0'
 17
 18 gem 'coffee-rails', '~> 4.2'
 19 gem 'turbolinks', '~> 5'
 20 gem 'jbuilder', '~> 2.5'
 21
 22 gem "refinerycms-blog", git: "https://github.com/refinery/refinerycms-blog"
 23
 24 group :development, :test do
 25   gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
 26   gem 'capybara', '~> 2.13'
 27   gem 'selenium-webdriver'
 28 end
 29
 30 group :development do
 31   gem 'web-console', '>= 3.3.0'
 32   gem 'listen', '>= 3.0.5', '< 3.2'
 33   gem 'spring'
 34   gem 'spring-watcher-listen', '~> 2.0.0'
 35 end
 36
 37 gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

**Comment by bricesanchez** [comment]
Hi @iiewad, Thanks for trying this underused feature!

It seems like `globalize` is not loaded at the moment you want to run migrations.

Could you try this branch in your Gemfile to see if it fixed your error : 
```
gem "refinerycms-blog", git: "https://github.com/refinery/refinerycms-blog", branch: "bugfix/3344/require-globalize"
```

**Comment by iiewad** [comment]
@bricesanchez I will try it, later. Thanks you very much!

**Comment by bricesanchez** [comment]
@iiewad let me know if it works!
