### ISSUE TITLE
Initializing with Rails 5.2.1 fails: devise/actionmailer version conflict

### ISSUE THREAD

**Issue by brentkearney** [refinery/refinerycms#3414]
After running:
`bundle exec rails new netmojo -m http://refinerycms.com/t/edge`

I get:

```
cms    | Initializing Rails...
...
cms    |       remove  config/initializers/new_framework_defaults_5_2.rb
cms    |        apply  http://refinerycms.com/t/edge
cms    |       append    Gemfile
cms    |       append    Gemfile
cms    |          run    bundle install from "."
...
cms    | Using actionview 5.2.1
cms    | Using actionpack 5.2.1
cms    | Using actioncable 5.2.1
cms    | Using activerecord 5.2.1
cms    | Using refinerycms-i18n 5.0.0
cms    | Using refinerycms-core 4.0.2 from https://github.com/refinery/refinerycms (at master@13048b1)
cms    | Using refinerycms-dragonfly 1.0.0 from https://github.com/refinery/refinerycms (at master@13048b1)
cms    | Using refinerycms-images 4.0.2 from https://github.com/refinery/refinerycms (at master@13048b1)
cms    | Using refinerycms-pages 4.0.2 from https://github.com/refinery/refinerycms (at master@13048b1)
cms    | Using refinerycms-resources 4.0.2 from https://github.com/refinery/refinerycms (at master@13048b1)
cms    | Using refinerycms 4.0.2 from https://github.com/refinery/refinerycms (at master@13048b1)
...
cms    | Bundle complete! 5 Gemfile dependencies, 93 gems now installed.
cms    | Use `bundle info [gemname]` to see where a bundled gem is installed.
cms    |         rake    db:create
cms    | rake aborted!
cms    | LoadError: cannot load such file -- bootsnap/setup
cms    | /home/app/netmojo/config/boot.rb:4:in `require'
cms    | /home/app/netmojo/config/boot.rb:4:in `<top (required)>'
cms    | /home/app/netmojo/config/application.rb:1:in `require_relative'
cms    | /home/app/netmojo/config/application.rb:1:in `<top (required)>'
cms    | /home/app/netmojo/Rakefile:4:in `require_relative'
cms    | /home/app/netmojo/Rakefile:4:in `<top (required)>'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
cms    | (See full trace by running task with --trace)
cms    |     generate    refinery:cms --fresh-installation new netmojo -m http://refinerycms.com/t/edge
cms    | /home/app/netmojo/config/boot.rb:4:in `require': cannot load such file -- bootsnap/setup (LoadError)
cms    | 	from /home/app/netmojo/config/boot.rb:4:in `<top (required)>'
cms    | 	from bin/rails:3:in `require_relative'
cms    | 	from bin/rails:3:in `<main>'
cms    |     ============================================================================
cms    |     Your new Refinery CMS application is now running on edge and mounted to /.
cms    |   ============================================================================
cms    |          run  bundle install
cms    | Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
cms    | installing your bundle as root will break this application for all non-root
cms    | users on this machine.
cms    | Fetching https://github.com/refinery/refinerycms
cms    | The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
cms    | Fetching gem metadata from https://rubygems.org/.........
cms    | Fetching gem metadata from https://rubygems.org/.
cms    | Resolving dependencies...
cms    | Bundler could not find compatible versions for gem "actionmailer":
cms    |   In Gemfile:
cms    |     rails (~> 5.2.1) was resolved to 5.2.1, which depends on
cms    |       actionmailer (= 5.2.1)
cms    | 
cms    | refinerycms-authentication-devise (~> 2.0) was resolved to 2.0.0, which
cms    | depends on
cms    |       actionmailer (>= 5.0.0, < 5.2)
...
cms exited with code 1
```

It appears that this actionamailer < 5.2 dependency was removed from the refinerycms-authentication-devise gem: [https://github.com/refinery/refinerycms-authentication-devise/pull/40](https://github.com/refinery/refinerycms-authentication-devise/pull/40). So that means refinerycms is referencing an older version.

**Comment by brentkearney** [comment]
I used a local copy of the script at: https://www.refinerycms.com/t/edge, replacing the `gem 'refinerycms-authentication-devise'...` line with:
```
gem 'refinerycms-authentication-devise', git: 'https://github.com/refinery/refinerycms-authentication-devise', branch: 'master'
```

That seems to work, but then it gets hung up trying to install the msgpack gem:

```
cms    | Fetching msgpack 1.2.4
cms    | Installing msgpack 1.2.4 with native extensions
cms    | Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
cms    | 
cms    | current directory:
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/msgpack-1.2.4/ext/msgpack
cms    | /usr/local/rvm/rubies/ruby-2.5.3/bin/ruby -r ./siteconf20181119-271-1opz4iw.rb
cms    | extconf.rb
cms    | checking for ruby/st.h... *** extconf.rb failed ***
cms    | Could not create Makefile due to some reason, probably lack of necessary
cms    | libraries and/or headers.  Check the mkmf.log file for more details.  You may
cms    | need configuration options.
```

The mkmf.log says:
```
In file included from /usr/local/rvm/rubies/ruby-2.5.3/include/ruby-2.5.0/ruby/defines.h:112:0,
                 from /usr/local/rvm/rubies/ruby-2.5.3/include/ruby-2.5.0/ruby/ruby.h:29,
                 from /usr/local/rvm/rubies/ruby-2.5.3/include/ruby-2.5.0/ruby.h:33,
                 from conftest.c:1:
/usr/include/stdio.h:27:10: fatal error: bits/libc-header-start.h: No such file or directory
 #include <bits/libc-header-start.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

This is an Ubuntu 18.04 system. A [search of all Ubuntu packages](https://packages.ubuntu.com) for this file comes up empty. :/

**Comment by brentkearney** [comment]
I removed the bootsnap gem from the Gemfile, and commented it out from config/boot.rb. Then the `bundle install` completes, and I get to: 

```
cms    | Compiling Assets...
cms    | ** Invoke assets:precompile (first_time)
cms    | ** Invoke assets:environment (first_time)
cms    | ** Execute assets:environment
cms    | ** Invoke environment (first_time)
cms    | ** Execute environment
cms    | ** Invoke yarn:install (first_time)
cms    | ** Execute yarn:install
cms    | yarn install v1.12.3
cms    | info No lockfile found.
cms    | [1/4] Resolving packages...
cms    | [2/4] Fetching packages...
cms    | [3/4] Linking dependencies...
cms    | [4/4] Building fresh packages...
cms    | success Saved lockfile.
cms    | Done in 0.12s.
cms    | ** Execute assets:precompile
cms    | rake aborted!
cms    | Uglifier::Error: Unexpected token: keyword (const). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true).
cms    | /usr/local/rvm/gems/ruby-2.5.3/bundler/gems/refinerycms-13048b142b8d/core/app/assets/config/refinery_core_manifest.js:19
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/uglifier-4.1.20/lib/uglifier.rb:234:in `parse_result'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/uglifier-4.1.20/lib/uglifier.rb:216:in `run_uglifyjs'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/uglifier-4.1.20/lib/uglifier.rb:168:in `compile'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/uglifier_compressor.rb:53:in `call'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/uglifier_compressor.rb:28:in `call'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/directive_processor.rb:388:in `load'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/directive_processor.rb:300:in `process_link_directive'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/directive_processor.rb:180:in `block in process_directives'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/directive_processor.rb:178:in `each'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/directive_processor.rb:178:in `process_directives'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/directive_processor.rb:83:in `_call'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/directive_processor.rb:68:in `call'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:23:in `block in call'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/utils.rb:200:in `dfs'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:24:in `call'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/base.rb:66:in `find_asset'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/base.rb:73:in `find_all_linked_assets'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:134:in `block in find'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:133:in `each'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:133:in `find'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:186:in `compile'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/rake/sprocketstask.rb:147:in `with_logger'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
cms    | /usr/local/rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
cms    | /usr/local/rvm/gems/ruby-2.5.3/bin/rake:23:in `load'
cms    | /usr/local/rvm/gems/ruby-2.5.3/bin/rake:23:in `<top (required)>'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `load'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:28:in `run'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/cli.rb:463:in `exec'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/cli.rb:27:in `dispatch'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/cli.rb:18:in `start'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/exe/bundle:30:in `block in <top (required)>'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
cms    | /usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/exe/bundle:22:in `<top (required)>'
cms    | /usr/local/rvm/gems/ruby-2.5.3/bin/bundle:23:in `load'
cms    | /usr/local/rvm/gems/ruby-2.5.3/bin/bundle:23:in `<main>'
cms    | /usr/local/rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `eval'
cms    | /usr/local/rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `<main>'
cms    | Tasks: TOP => assets:precompile
```

**Comment by bricesanchez** [comment]
Thanks for your report @brentkearney !
