### ISSUE TITLE
Can't Run Refinery - active support errors

### ISSUE THREAD

**Issue by Supaiku** [refinery/refinerycms#3516]
In production mode:

=> Booting Puma
=> Rails 5.1.7 application starting in production
=> Run `rails server -h` for more startup options
Exiting
/home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-5.1.7/lib/active_support/core_ext/module/delegation.rb:157:in `delegate': Delegation needs a target. Supply an options hash with a :to key as the last argument (e.g. delegate :hello, to: :greeter). (ArgumentError)
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/refinerycms-pages-4.0.3/app/models/refinery/page.rb:50:in `<class:Page>'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/refinerycms-pages-4.0.3/app/models/refinery/page.rb:8:in `<module:Refinery>'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/refinerycms-pages-4.0.3/app/models/refinery/page.rb:7:in `<top (required)>'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:292:in `require'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:292:in `block in require'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:258:in `load_dependency'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:292:in `require'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:379:in `block in require_or_load'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:36:in `block in load_interlock'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-5.1.7/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-5.1.7/lib/active_support/concurrency/share_lock.rb:149:in `exclusive'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-5.1.7/lib/active_support/dependencies/interlock.rb:11:in `loading'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:36:in `load_interlock'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:357:in `require_or_load'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:511:in `load_missing_constant'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:202:in `const_missing'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-5.1.7/lib/active_support/inflector/methods.rb:271:in `const_get'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-5.1.7/lib/active_support/inflector/methods.rb:271:in `block in constantize'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-5.1.7/lib/active_support/inflector/methods.rb:267:in `each'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-5.1.7/lib/active_support/inflector/methods.rb:267:in `inject'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-5.1.7/lib/active_support/inflector/methods.rb:267:in `constantize'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-5.1.7/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/refinerycms-core-4.0.3/lib/refinery/crud.rb:22:in `default_options'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/refinerycms-core-4.0.3/lib/refinery/crud.rb:51:in `crudify'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/refinerycms-pages-4.0.3/app/controllers/refinery/admin/pages_controller.rb:6:in `<class:PagesController>'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/refinerycms-pages-4.0.3/app/controllers/refinery/admin/pages_controller.rb:3:in `<module:Admin>'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/refinerycms-pages-4.0.3/app/controllers/refinery/admin/pages_controller.rb:2:in `<module:Refinery>'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/refinerycms-pages-4.0.3/app/controllers/refinery/admin/pages_controller.rb:1:in `<top (required)>'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:292:in `require'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:292:in `block in require'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:258:in `load_dependency'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:292:in `require'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:379:in `block in require_or_load'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:36:in `block in load_interlock'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-5.1.7/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-5.1.7/lib/active_support/concurrency/share_lock.rb:149:in `exclusive'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-5.1.7/lib/active_support/dependencies/interlock.rb:11:in `loading'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:36:in `load_interlock'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:357:in `require_or_load'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:335:in `depend_on'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:251:in `require_dependency'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-5.1.7/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-5.1.7/lib/rails/engine.rb:475:in `each'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-5.1.7/lib/rails/engine.rb:475:in `block in eager_load!'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-5.1.7/lib/rails/engine.rb:473:in `each'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-5.1.7/lib/rails/engine.rb:473:in `eager_load!'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-5.1.7/lib/rails/engine.rb:354:in `eager_load!'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-5.1.7/lib/rails/application/finisher.rb:67:in `each'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-5.1.7/lib/rails/application/finisher.rb:67:in `block in <module:Finisher>'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-5.1.7/lib/rails/initializable.rb:30:in `instance_exec'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-5.1.7/lib/rails/initializable.rb:30:in `run'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-5.1.7/lib/rails/initializable.rb:59:in `block in run_initializers'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/3.0.0/tsort.rb:347:in `each'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/3.0.0/tsort.rb:347:in `call'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-5.1.7/lib/rails/initializable.rb:58:in `run_initializers'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-5.1.7/lib/rails/application.rb:353:in `initialize!'
        from /var/www/avlgoclub/config/environment.rb:5:in `<top (required)>'
        from config.ru:3:in `require_relative'
        from config.ru:3:in `block in <main>'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/builder.rb:116:in `eval'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/builder.rb:116:in `new_from_string'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/builder.rb:105:in `load_file'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/builder.rb:66:in `parse_file'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/server.rb:349:in `build_app_and_options_from_config'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/server.rb:249:in `app'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-5.1.7/lib/rails/commands/server/server_command.rb:24:in `app'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/server.rb:422:in `wrapped_app'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/server.rb:312:in `block in start'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/server.rb:379:in `handle_profiling'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/server.rb:311:in `start'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-5.1.7/lib/rails/commands/server/server_command.rb:44:in `start'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-5.1.7/lib/rails/commands/server/server_command.rb:135:in `block in perform'
        from <internal:kernel>:90:in `tap'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-5.1.7/lib/rails/commands/server/server_command.rb:130:in `perform'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-5.1.7/lib/rails/command/base.rb:63:in `perform'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-5.1.7/lib/rails/command.rb:44:in `invoke'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-5.1.7/lib/rails/commands.rb:16:in `<top (required)>'
        from /var/www/avlgoclub/bin/rails:9:in `require'
        from /var/www/avlgoclub/bin/rails:9:in `<top (required)>'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
        from <internal:/home/supaiku/.rbenv/versions/3.0.4/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/supaiku/.rbenv/versions/3.0.4/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /var/www/avlgoclub/bin/spring:15:in `<top (required)>'
        from bin/rails:3:in `load'
        from bin/rails:3:in `<main>'

In development:

=> Booting Puma
=> Rails 5.1.7 application starting in development
=> Run `rails server -h` for more startup options
Exiting
/home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/static.rb:109:in `initialize': wrong number of arguments (given 3, expected 2) (ArgumentError)
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/stack.rb:35:in `new'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/stack.rb:35:in `build'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/stack.rb:99:in `block in build'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/stack.rb:99:in `each'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/stack.rb:99:in `inject'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/stack.rb:99:in `build'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-5.1.7/lib/rails/engine.rb:508:in `block in app'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-5.1.7/lib/rails/engine.rb:504:in `synchronize'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-5.1.7/lib/rails/engine.rb:504:in `app'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-5.1.7/lib/rails/application/finisher.rb:45:in `block in <module:Finisher>'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-5.1.7/lib/rails/initializable.rb:30:in `instance_exec'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-5.1.7/lib/rails/initializable.rb:30:in `run'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-5.1.7/lib/rails/initializable.rb:59:in `block in run_initializers'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/3.0.0/tsort.rb:347:in `each'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/3.0.0/tsort.rb:347:in `call'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-5.1.7/lib/rails/initializable.rb:58:in `run_initializers'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-5.1.7/lib/rails/application.rb:353:in `initialize!'
        from /var/www/avlgoclub/config/environment.rb:5:in `<top (required)>'
        from config.ru:3:in `require_relative'
        from config.ru:3:in `block in <main>'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/builder.rb:116:in `eval'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/builder.rb:116:in `new_from_string'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/builder.rb:105:in `load_file'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/builder.rb:66:in `parse_file'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/server.rb:349:in `build_app_and_options_from_config'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/server.rb:249:in `app'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-5.1.7/lib/rails/commands/server/server_command.rb:24:in `app'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/server.rb:422:in `wrapped_app'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-5.1.7/lib/rails/commands/server/server_command.rb:80:in `log_to_stdout'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-5.1.7/lib/rails/commands/server/server_command.rb:42:in `start'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-5.1.7/lib/rails/commands/server/server_command.rb:135:in `block in perform'
        from <internal:kernel>:90:in `tap'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-5.1.7/lib/rails/commands/server/server_command.rb:130:in `perform'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-5.1.7/lib/rails/command/base.rb:63:in `perform'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-5.1.7/lib/rails/command.rb:44:in `invoke'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-5.1.7/lib/rails/commands.rb:16:in `<top (required)>'
        from /var/www/avlgoclub/bin/rails:9:in `require'
        from /var/www/avlgoclub/bin/rails:9:in `<top (required)>'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
        from /home/supaiku/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
        from <internal:/home/supaiku/.rbenv/versions/3.0.4/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/supaiku/.rbenv/versions/3.0.4/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /var/www/avlgoclub/bin/spring:15:in `<top (required)>'
        from bin/rails:3:in `load'
        from bin/rails:3:in `<main>'

**Comment by Matho** [comment]
Hi @Supaiku

I think your problem is, that you are trying to use Rails 5.1.7 with Ruby 3.0

Rails 5.1.7 is old. If you are starting new project, you can check this RefineryCMS demo apps: 
1) https://github.com/refinery/refinerycms-example-app (Rails 6.0.2, ruby-2.6.5) 
2) or its fork  https://github.com/Matho/refinerycms-example-app , if you want to use Docker

If you want to use Ruby 3.0+, you can check this gist about project ugprade https://gist.github.com/Matho/3587bd01c14f0e0bf60bf4bca3b733ec (but some of the hacks mentioned here are not the best and proper solution)

I'm running Refinery on Ruby 3.1.0 on one of my project. The only change between Ruby 3.0.3 and 3.1.0 was to update ruby version in Gemfile + add `gem 'psych', '~> 3.3.2'` at the end of Gemfile.

Martin

**Comment by Supaiku** [comment]
Thanks - for some reason this is what was installed when I used rbenv on
this Digital Ocaen Ubuntu droplet... I thought it was like that on purpose
since the gemfile had these versions.

Why would the gemfile give me these older versions if it's not intentional?

**Comment by ttmthanh** [comment]
@Matho I got this error when I tried upgrade ruby 3.0.3. Can you help me fix this :'( 

![image](https://user-images.githubusercontent.com/22828586/179693905-f55182df-c324-4759-a600-6fb2ba723293.png)

**Comment by Matho** [comment]
@ttmthanh Hi. Which version of Refinery you are using? Do you use the version from master branch? Is it possible to share the whole project with me?

**Comment by ttmthanh** [comment]
@Matho I use version from master branch. How can I share with you?

**Comment by Matho** [comment]
@ttmthanh  Currently, the master branch doesnt support Ruby 3.0 The last supported Ruby for this project is 2.6.X 

If you want to run on Ruby 3+, you can chcek this gist https://gist.github.com/Matho/3587bd01c14f0e0bf60bf4bca3b733ec already mentioned in this thread. Note: This steps works only for the case, you do not need multiple locales in your project. The Mobility config is not correctly setup.

**Comment by ttmthanh** [comment]
@Matho Thank you. I think I will use Ruby 2.7.6 until Refinery support for Ruby 3.x.x

**Comment by parndt** [comment]
Fixed by #3518
